# Use an official Ubuntu as a base image
FROM ubuntu:22.04

# Set the environment to non-interactive to avoid any prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update and install required packages
RUN apt-get update && apt-get install -y \
    build-essential \
    gdb \
    valgrind \
    linux-tools-common \
    linux-tools-generic \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Set the default command to execute bash
CMD ["/bin/bash"]
